environment        = "prod"
aws_region         = "us-east-1"
vpc_cidr           = "10.1.0.0/16"
rds_instance_class = "db.t3.medium"
db_username        = "dbadmin_prod"
db_password        = "ProdUltraSecurePass456!"
